## This is a ipynb file for test.

In [ ]:
%pip install pandas
%pip install tensorflow
%pip install tf_agents

In [2]:
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

import tensorflow as tf
from tf_agents.trajectories import time_step as ts

import absl
import time
import os
import glob

import pandas as pd
import numpy as np

import logging


# Generating dataset from csv file. Returns a Pandas DataFrame
def entire_dataset_from_single_file(filename,
                                    col_names,
                                    selected_col_names,
                                    remove_zero_req_prb_entries=True,
                                    scale_dl_buffer=True,
                                    replace_zero_with_one=False,
                                    add_prb_ratio=True):
    dataset = pd.read_csv(filename, names=col_names, usecols=selected_col_names, header=0)

    if remove_zero_req_prb_entries:
        dataset = dataset.loc[dataset['sum_requested_prbs'] > 0].reset_index(drop=True)

    if scale_dl_buffer and any(["dl_buffer [bytes]" in m for m in
                                selected_col_names]):
        # scale the dl_buffer
        dataset['dl_buffer [bytes]'] = dataset['dl_buffer [bytes]'] / 100000

    if add_prb_ratio:
        dict_add = pd.DataFrame.from_dict({"ratio_granted_req": np.clip(np.nan_to_num(
            dataset["sum_granted_prbs"] / dataset["sum_requested_prbs"]), a_min=0, a_max=1)
        })
        if replace_zero_with_one:
            dict_add['ratio_granted_req'].loc[dataset['sum_requested_prbs'] <= 0] = 1.0
        return dataset.join(dict_add)
    else:
        return dataset

# return all csv files inside a single DataFrame
def entire_dataset_from_folder(main_folder,
                               wildcard,
                               col_names,
                               selected_col_names,
                               scale_dl_buffer=True,
                               remove_zero_req_prb_entries=True,
                               replace_zero_with_one=False,
                               add_prb_ratio=True):
    dataset = []
    for filename in glob.glob(main_folder + wildcard):
        db_tmp = entire_dataset_from_single_file(filename, col_names=col_names,
                                                 selected_col_names=selected_col_names,
                                                 scale_dl_buffer=scale_dl_buffer,
                                                 remove_zero_req_prb_entries=remove_zero_req_prb_entries,
                                                 replace_zero_with_one=replace_zero_with_one,
                                                 add_prb_ratio=add_prb_ratio)
        dataset.append(db_tmp)

    return pd.concat(dataset, axis=0, ignore_index=True)


# take n entries from the DataFrame at random
def extract_n_entries_from_dataset(dataset=None,
                                   slice_id=None,
                                   n_entries=10,
                                   metrics_export=None):
    if slice_id is not None:
        d_temp = dataset.loc[dataset['slice_id'] == int(slice_id)]
    else:
        d_temp = dataset

    d_temp = d_temp.sample(n=n_entries).reset_index(drop=True)
    if metrics_export is not None:
        d_temp = d_temp[metrics_export]

    return d_temp

# This function is used here to emulate a DU reporting real-time data. Replace this function with your DU
# FOR TESTING PURPOSES ONLY
def get_data_from_DUs(dataset=None,
                      n_entries=1000,
                      n_col=4,
                      slice_id=None,
                      metrics_export=None):

    if dataset is None:  # generate random data in case you do not have a dataset
        values = np.random.random(size=(n_entries, n_col))
        slice_id = np.random.randint(low=0, high=3, size=(n_entries, 1))
        data = np.concatenate((slice_id, values), axis=1)
    else:
        data = extract_n_entries_from_dataset(dataset=dataset,
                                              slice_id=slice_id,
                                              n_entries=n_entries,
                                              metrics_export=metrics_export)

    return data


# Return lists for metrics, rewards, prbs assigned to each slice.
# Ideally, the list is such that len(list) = num_slices
def split_data(slice_profiles=None,
               data_to_spit=None,
               metric_list=None,
               metric_dict=None,
               n_entries_per_slice=None):
    metrics = []
    prbs = []
    rewards = []

    # ordering here follows slice_profiles
    for i in slice_profiles:

        slice_data = data_to_spit[data_to_spit[:, metric_dict['slice_id']] == slice_profiles[i]['slice_id'], :]

        if slice_data.size > 0:
            # repmat on rows to reach needed dimension in case you do not have enough reporting data
            while slice_data.shape[0] < n_entries_per_slice:
                slice_data = np.vstack((slice_data, np.zeros((1, slice_data.shape[1]))))

            slice_prb = slice_data[:, metric_dict['slice_prb']]
            slice_metrics = slice_data[:, [metric_dict[x] for x in metric_list]]
            slice_reward = slice_data[:, metric_dict[slice_profiles[i]['reward_metric']]]

            if n_entries_per_slice is not None:
                slice_prb = slice_prb[0:n_entries_per_slice]
                slice_metrics = slice_metrics[0:n_entries_per_slice, :]
                slice_reward = slice_reward[0:n_entries_per_slice]
        else:
            slice_metrics = []
            slice_prb = []
            slice_reward = []

        metrics.append(slice_metrics)
        prbs.append(slice_prb)
        rewards.append(slice_reward)

    return metrics, prbs, rewards

# Used to generate the input to the DRL agent. It returns a TimeStep that contains (step_type, reward, discount, observations)
def generate_timestep_for_policy(obs_tmp=None):
    step_type = tf.convert_to_tensor(
        [0], dtype=tf.int32, name='step_type')
    reward = tf.convert_to_tensor(
        [0], dtype=tf.float32, name='reward')
    discount = tf.convert_to_tensor(
        [1], dtype=tf.float32, name='discount')
    observations = tf.convert_to_tensor(
        [obs_tmp], dtype=tf.float32, name='observations')
    return ts.TimeStep(step_type, reward, discount, observations)


if __name__ == '__main__':

    # Column names in the srsLTE CSV dataset
    all_metrics_list = ["Timestamp",
                        "num_ues",
                        "IMSI",
                        "RNTI",
                        "empty_1",
                        "slicing_enabled",
                        "slice_id",
                        "slice_prb",
                        "power_multiplier",
                        "scheduling_policy",
                        "empty_2",
                        "dl_mcs",
                        "dl_n_samples",
                        "dl_buffer [bytes]",
                        "tx_brate downlink [Mbps]",
                        "tx_pkts downlink",
                        "tx_errors downlink (%)",
                        "dl_cqi",
                        "empty_3",
                        "ul_mcs",
                        "ul_n_samples",
                        "ul_buffer [bytes]",
                        "rx_brate uplink [Mbps]",
                        "rx_pkts uplink",
                        "rx_errors uplink (%)",
                        "ul_rssi",
                        "ul_sinr",
                        "phr",
                        "empty_4",
                        "sum_requested_prbs",
                        "sum_granted_prbs",
                        "empty_5",
                        "dl_pmi",
                        "dl_ri",
                        "ul_n",
                        "ul_turbo_iters"]

    # Column names we need to extract from the dataset
    metric_list_to_extract = ["slice_id",
                              "dl_buffer [bytes]",
                              "tx_brate downlink [Mbps]",
                              "sum_requested_prbs",
                              "sum_granted_prbs"]

    # configure logger and console output
    logging.basicConfig(level=logging.DEBUG, filename='./log.txt', filemode='w+',
                        format='%(asctime)-15s %(levelname)-8s %(message)s')
    formatter = logging.Formatter('%(asctime)-15s %(levelname)-8s %(message)s')
    console = logging.StreamHandler()
    console.setLevel(logging.INFO)
    console.setFormatter(formatter)
    logging.getLogger('').addHandler(console)

    use_gpu_in_env = True
    mtc_policy_filename = './ml_models/mtc_policy'
    urllc_policy_filename = './ml_models/urllc_policy'
    embb_policy_filename = './ml_models/embb_policy'
    autoencoder_filename = './ml_models/encoder.h5'

    # Location of the dataset we want to use (valid in offline testing ONLY)
    main_folder = './slice_traffic/rome_static_close/tr10'
    wildcard_match = '/*/*/slices_bs*/*_metrics.csv'

    # get dataset for testing purposes only.
    # This is used as this code does not run with hardware components.
    # Not needed if getting data from real DUs
    dataset = entire_dataset_from_folder(main_folder=main_folder,
                                         wildcard=wildcard_match,
                                         col_names=all_metrics_list,
                                         selected_col_names=metric_list_to_extract)

    # Input size to the autoencoder for dimentionality reduction
    n_entries_for_autoencoder = 10

    # set logging level + enable TF2 behavior
    absl.logging.set_verbosity(absl.logging.INFO)
    # select which GPU to use
    os.environ["CUDA_VISIBLE_DEVICES"] = "0"

    if use_gpu_in_env is False:
        gpu_devices = tf.config.experimental.list_physical_devices('GPU')
        tf.config.experimental.set_memory_growth(gpu_devices[0], True)
        print("Num GPUs Available outside environments: ", len(gpu_devices))

    # load policy, these are the folder where saved_model.pb is stored
    drl_agents = [tf.saved_model.load(embb_policy_filename),
                  tf.saved_model.load(mtc_policy_filename),
                  tf.saved_model.load(urllc_policy_filename)]

    absl.logging.info('Agents loaded')

    autoencoder = tf.keras.models.load_model(autoencoder_filename)

    absl.logging.info('Autoencoder loaded')

    slice_profiles = {'embb': {'slice_id': 0, 'reward_metric': "tx_brate downlink [Mbps]"},
                      'mtc': {'slice_id': 1, 'reward_metric': "tx_brate downlink [Mbps]"},
                      'urllc': {'slice_id': 2, 'reward_metric': "ratio_granted_req"}}

    metric_dict = {"dl_buffer [bytes]": 1,
                   "tx_brate downlink [Mbps]": 2,
                   "ratio_granted_req": 3,
                   "slice_id": 0,
                   "slice_prb": 4}

    metric_list_for_agents = ["dl_buffer [bytes]",
                   "tx_brate downlink [Mbps]",
                   "ratio_granted_req"]

    default_policy = 0
    previous_policy = dict()
    for _, val in slice_profiles.items():
        previous_policy[val['slice_id']] = default_policy

    previous_metrics = ''

    while True:
        policies = list()

        # This is where data comes from the DUs.
        # As an example, we extract data from the static dataset.
        # Users may want to interface it with their own DUs
        data = get_data_from_DUs(dataset=dataset,
                                 n_entries=1000,
                                 metrics_export=metric_list_to_extract).to_numpy()

        data_tmp, prbs, rewards = split_data(slice_profiles=slice_profiles,
                                             data_to_spit=data,
                                             metric_dict=metric_dict,
                                             metric_list=metric_list_for_agents,
                                             n_entries_per_slice=n_entries_for_autoencoder)

        for i in range(len(slice_profiles)):
            if len(data_tmp[i]) > 0:
                for row in data_tmp[i]:
                    row[0] /= 100000

                logging.info('Testing iteration ' + str(i))
                logging.info('Data received from DU (dl_buffer [bytes], tx_brate downlink [Mbps], ratio_granted_req): ')
                logging.info(np.expand_dims(data_tmp[i], axis=0))

                obs_tmp = autoencoder.predict(np.expand_dims(data_tmp[i], axis=0)).astype('float32')
                obs_tmp = np.append(obs_tmp, prbs[i][0]).astype('float32')

                reward_mean = np.mean(rewards[i]).astype('float32')
                time_step = generate_timestep_for_policy(obs_tmp)
                action = drl_agents[i].action(time_step)

                # append policies to send and store policy
                policies.append(action[0][0][0].numpy())
                previous_policy[i] = action[0][0][0].numpy()

                logging.info('Slice ' + str(i) + ': Action is ' + str(action[0][0][0].numpy()) + ' Reward is: ' + str(
                    reward_mean))
            else:
                # append previous policy
                policies.append(previous_policy[i])
                logging.info('Using previous action ' + str(previous_policy[i]) + ' for slice profile ' + str(i))

        # build message to send policies to the DU
        msg = ','.join([str(x) for x in policies])
        logging.info('Sending this message to the DU: ' + msg)

        time.sleep(10)

        # Users may want to plug in their own functions to send the DRL policies
        # to the DU based on the specific DU implementation in use
        # send_action_to_DU(DU_address, msg)


2023-04-05 17:49:42,560 INFO     Testing iteration 0
2023-04-05 17:49:42,560 INFO     Testing iteration 0
2023-04-05 17:49:42,561 INFO     Data received from DU (dl_buffer [bytes], tx_brate downlink [Mbps], ratio_granted_req): 
2023-04-05 17:49:42,561 INFO     Data received from DU (dl_buffer [bytes], tx_brate downlink [Mbps], ratio_granted_req): 
2023-04-05 17:49:42,562 INFO     [[[0.00000e+00 9.77285e-01 4.73000e+02]
  [7.45000e-08 9.79872e-01 5.30000e+02]
  [9.56900e-07 7.25824e-01 3.80000e+01]
  [1.43300e-07 9.53920e-01 6.54000e+02]
  [7.61000e-08 9.81632e-01 4.23000e+02]
  [1.08700e-07 9.60224e-01 6.40000e+02]
  [9.69000e-08 1.15222e+00 4.50000e+01]
  [7.19100e-07 9.54848e-01 2.42000e+02]
  [8.10000e-09 9.81912e-01 7.34000e+02]
  [0.00000e+00 9.80273e-01 4.93000e+02]]]
2023-04-05 17:49:42,562 INFO     [[[0.00000e+00 9.77285e-01 4.73000e+02]
  [7.45000e-08 9.79872e-01 5.30000e+02]
  [9.56900e-07 7.25824e-01 3.80000e+01]
  [1.43300e-07 9.53920e-01 6.54000e+02]
  [7.61000e-08 9.81632

1/1 [==============================] - 0s 15ms/step


2023-04-05 17:49:42,603 INFO     Slice 0: Action is 1 Reward is: 0.964801
2023-04-05 17:49:42,603 INFO     Slice 0: Action is 1 Reward is: 0.964801
2023-04-05 17:49:42,604 INFO     Testing iteration 1
2023-04-05 17:49:42,604 INFO     Testing iteration 1
2023-04-05 17:49:42,605 INFO     Data received from DU (dl_buffer [bytes], tx_brate downlink [Mbps], ratio_granted_req): 
2023-04-05 17:49:42,605 INFO     Data received from DU (dl_buffer [bytes], tx_brate downlink [Mbps], ratio_granted_req): 
2023-04-05 17:49:42,606 INFO     [[[0.00000e+00 3.71727e-02 1.48000e+02]
  [0.00000e+00 5.27550e-02 3.50000e+02]
  [0.00000e+00 5.71520e-02 7.40000e+01]
  [1.58000e-08 3.24800e-02 8.50000e+01]
  [0.00000e+00 2.21120e-02 7.10000e+01]
  [0.00000e+00 3.74297e-02 1.09000e+02]
  [0.00000e+00 3.19040e-02 3.50000e+01]
  [2.32000e-08 6.33253e-02 2.61000e+02]
  [0.00000e+00 8.51200e-02 4.17000e+02]
  [0.00000e+00 2.67309e-02 7.80000e+01]]]
2023-04-05 17:49:42,606 INFO     [[[0.00000e+00 3.71727e-02 1.48000

1/1 [==============================] - 0s 15ms/step


2023-04-05 17:49:42,649 INFO     Slice 1: Action is 1 Reward is: 0.04461816
2023-04-05 17:49:42,649 INFO     Slice 1: Action is 1 Reward is: 0.04461816
2023-04-05 17:49:42,651 INFO     Testing iteration 2
2023-04-05 17:49:42,651 INFO     Testing iteration 2
2023-04-05 17:49:42,652 INFO     Data received from DU (dl_buffer [bytes], tx_brate downlink [Mbps], ratio_granted_req): 
2023-04-05 17:49:42,652 INFO     Data received from DU (dl_buffer [bytes], tx_brate downlink [Mbps], ratio_granted_req): 
2023-04-05 17:49:42,653 INFO     [[[0.00000e+00 2.48675e-02 1.48000e+02]
  [0.00000e+00 1.10720e-02 1.10000e+01]
  [0.00000e+00 1.06667e-02 6.00000e+00]
  [0.00000e+00 1.03454e-02 8.00000e+00]
  [0.00000e+00 6.32932e-03 4.90000e+01]
  [0.00000e+00 1.89237e-02 1.58000e+02]
  [0.00000e+00 5.33333e-03 6.00000e+00]
  [0.00000e+00 5.31200e-03 6.00000e+00]
  [0.00000e+00 1.08160e-02 1.60000e+01]
  [0.00000e+00 1.68996e-02 3.40000e+01]]]
2023-04-05 17:49:42,653 INFO     [[[0.00000e+00 2.48675e-02 1.4

1/1 [==============================] - 0s 15ms/step


2023-04-05 17:49:42,698 INFO     Slice 2: Action is 1 Reward is: 44.2
2023-04-05 17:49:42,698 INFO     Slice 2: Action is 1 Reward is: 44.2
2023-04-05 17:49:42,699 INFO     Sending this message to the DU: 1,1,1
2023-04-05 17:49:42,699 INFO     Sending this message to the DU: 1,1,1
2023-04-05 17:49:52,706 INFO     Testing iteration 0
2023-04-05 17:49:52,706 INFO     Testing iteration 0
2023-04-05 17:49:52,707 INFO     Data received from DU (dl_buffer [bytes], tx_brate downlink [Mbps], ratio_granted_req): 
2023-04-05 17:49:52,707 INFO     Data received from DU (dl_buffer [bytes], tx_brate downlink [Mbps], ratio_granted_req): 
2023-04-05 17:49:52,709 INFO     [[[8.89000e-08 9.71104e-01 5.94000e+02]
  [3.17400e-07 9.12032e-01 4.78000e+02]
  [0.00000e+00 9.61216e-01 7.37000e+02]
  [2.62200e-07 9.34368e-01 4.80000e+02]
  [0.00000e+00 9.74876e-01 6.67000e+02]
  [0.00000e+00 9.80627e-01 5.66000e+02]
  [2.38000e-07 9.34432e-01 5.65000e+02]
  [5.37000e-08 9.62474e-01 6.72000e+02]
  [1.14500e-07 

1/1 [==============================] - 0s 15ms/step


2023-04-05 17:49:52,751 INFO     Slice 0: Action is 1 Reward is: 0.9552283
2023-04-05 17:49:52,751 INFO     Slice 0: Action is 1 Reward is: 0.9552283
2023-04-05 17:49:52,752 INFO     Testing iteration 1
2023-04-05 17:49:52,752 INFO     Testing iteration 1
2023-04-05 17:49:52,753 INFO     Data received from DU (dl_buffer [bytes], tx_brate downlink [Mbps], ratio_granted_req): 
2023-04-05 17:49:52,753 INFO     Data received from DU (dl_buffer [bytes], tx_brate downlink [Mbps], ratio_granted_req): 
2023-04-05 17:49:52,754 INFO     [[[8.04000e-08 7.00402e-03 7.70000e+01]
  [0.00000e+00 5.25120e-02 1.05000e+02]
  [0.00000e+00 4.52480e-02 1.74000e+02]
  [0.00000e+00 3.94240e-02 9.30000e+01]
  [0.00000e+00 5.51647e-02 7.50000e+01]
  [3.70000e-09 4.84160e-02 1.68000e+02]
  [0.00000e+00 7.60161e-02 9.60000e+01]
  [0.00000e+00 2.35823e-02 2.47000e+02]
  [0.00000e+00 4.39680e-02 7.80000e+01]
  [0.00000e+00 5.28640e-02 1.15000e+02]]]
2023-04-05 17:49:52,754 INFO     [[[8.04000e-08 7.00402e-03 7.700

1/1 [==============================] - 0s 15ms/step


2023-04-05 17:49:52,799 INFO     Slice 1: Action is 1 Reward is: 0.04441991
2023-04-05 17:49:52,799 INFO     Slice 1: Action is 1 Reward is: 0.04441991
2023-04-05 17:49:52,801 INFO     Testing iteration 2
2023-04-05 17:49:52,801 INFO     Testing iteration 2
2023-04-05 17:49:52,802 INFO     Data received from DU (dl_buffer [bytes], tx_brate downlink [Mbps], ratio_granted_req): 
2023-04-05 17:49:52,802 INFO     Data received from DU (dl_buffer [bytes], tx_brate downlink [Mbps], ratio_granted_req): 
2023-04-05 17:49:52,803 INFO     [[[1.58000e-08 1.60643e-02 1.20000e+01]
  [0.00000e+00 1.07952e-02 8.00000e+00]
  [0.00000e+00 5.31200e-03 6.00000e+00]
  [0.00000e+00 1.05060e-02 1.70000e+01]
  [0.00000e+00 1.59357e-02 1.20000e+01]
  [0.00000e+00 1.60964e-02 9.00000e+00]
  [0.00000e+00 3.32209e-02 2.00000e+01]
  [0.00000e+00 1.06240e-02 4.70000e+01]
  [0.00000e+00 2.18560e-02 8.00000e+00]
  [0.00000e+00 2.13120e-02 3.30000e+01]]]
2023-04-05 17:49:52,803 INFO     [[[1.58000e-08 1.60643e-02 1.2

1/1 [==============================] - 0s 21ms/step


2023-04-05 17:49:52,859 INFO     Slice 2: Action is 2 Reward is: 17.2
2023-04-05 17:49:52,859 INFO     Slice 2: Action is 2 Reward is: 17.2
2023-04-05 17:49:52,860 INFO     Sending this message to the DU: 1,1,2
2023-04-05 17:49:52,860 INFO     Sending this message to the DU: 1,1,2
2023-04-05 17:50:02,867 INFO     Testing iteration 0
2023-04-05 17:50:02,867 INFO     Testing iteration 0
2023-04-05 17:50:02,868 INFO     Data received from DU (dl_buffer [bytes], tx_brate downlink [Mbps], ratio_granted_req): 
2023-04-05 17:50:02,868 INFO     Data received from DU (dl_buffer [bytes], tx_brate downlink [Mbps], ratio_granted_req): 
2023-04-05 17:50:02,869 INFO     [[[8.10000e-09 9.55552e-01 3.63000e+02]
  [1.64000e-08 1.04269e+00 1.81000e+02]
  [0.00000e+00 1.04469e+00 5.02000e+02]
  [1.43300e-07 9.61376e-01 3.62000e+02]
  [0.00000e+00 9.79936e-01 8.45000e+02]
  [0.00000e+00 9.60064e-01 7.16000e+02]
  [9.69000e-08 9.79213e-01 5.01000e+02]
  [0.00000e+00 9.60640e-01 5.73000e+02]
  [7.93100e-07 

1/1 [==============================] - 0s 14ms/step


2023-04-05 17:50:02,910 INFO     Slice 0: Action is 1 Reward is: 0.9863561
2023-04-05 17:50:02,910 INFO     Slice 0: Action is 1 Reward is: 0.9863561
2023-04-05 17:50:02,912 INFO     Testing iteration 1
2023-04-05 17:50:02,912 INFO     Testing iteration 1
2023-04-05 17:50:02,913 INFO     Data received from DU (dl_buffer [bytes], tx_brate downlink [Mbps], ratio_granted_req): 
2023-04-05 17:50:02,913 INFO     Data received from DU (dl_buffer [bytes], tx_brate downlink [Mbps], ratio_granted_req): 
2023-04-05 17:50:02,914 INFO     [[[0.00000e+00 3.48800e-02 9.60000e+01]
  [0.00000e+00 4.11245e-02 6.80000e+01]
  [1.58000e-08 8.34240e-02 1.68000e+02]
  [0.00000e+00 4.79040e-02 6.40000e+01]
  [1.58000e-08 2.20480e-02 1.30000e+01]
  [0.00000e+00 3.38560e-02 2.80000e+01]
  [0.00000e+00 1.59360e-02 9.00000e+01]
  [6.20000e-09 2.84800e-02 1.80000e+02]
  [1.50000e-09 2.72640e-02 5.34000e+02]
  [0.00000e+00 7.03293e-02 1.16000e+02]]]
2023-04-05 17:50:02,914 INFO     [[[0.00000e+00 3.48800e-02 9.600

1/1 [==============================] - 0s 14ms/step


2023-04-05 17:50:02,957 INFO     Slice 1: Action is 1 Reward is: 0.04052458
2023-04-05 17:50:02,957 INFO     Slice 1: Action is 1 Reward is: 0.04052458
2023-04-05 17:50:02,958 INFO     Testing iteration 2
2023-04-05 17:50:02,958 INFO     Testing iteration 2
2023-04-05 17:50:02,959 INFO     Data received from DU (dl_buffer [bytes], tx_brate downlink [Mbps], ratio_granted_req): 
2023-04-05 17:50:02,959 INFO     Data received from DU (dl_buffer [bytes], tx_brate downlink [Mbps], ratio_granted_req): 
2023-04-05 17:50:02,960 INFO     [[[0.00000e+00 1.30560e-02 1.09000e+02]
  [0.00000e+00 1.61285e-02 8.00000e+00]
  [0.00000e+00 1.94378e-02 1.70000e+01]
  [0.00000e+00 1.05600e-02 9.00000e+00]
  [0.00000e+00 5.31200e-03 2.00000e+00]
  [0.00000e+00 1.06560e-02 9.00000e+00]
  [0.00000e+00 2.15040e-02 6.50000e+01]
  [0.00000e+00 5.92000e-03 2.00000e+00]
  [1.23000e-08 1.15663e-02 6.10000e+01]
  [0.00000e+00 3.18080e-02 1.80000e+01]]]
2023-04-05 17:50:02,960 INFO     [[[0.00000e+00 1.30560e-02 1.0

1/1 [==============================] - 0s 14ms/step


2023-04-05 17:50:03,002 INFO     Slice 2: Action is 1 Reward is: 30.0
2023-04-05 17:50:03,002 INFO     Slice 2: Action is 1 Reward is: 30.0
2023-04-05 17:50:03,003 INFO     Sending this message to the DU: 1,1,1
2023-04-05 17:50:03,003 INFO     Sending this message to the DU: 1,1,1
2023-04-05 17:50:13,011 INFO     Testing iteration 0
2023-04-05 17:50:13,011 INFO     Testing iteration 0
2023-04-05 17:50:13,012 INFO     Data received from DU (dl_buffer [bytes], tx_brate downlink [Mbps], ratio_granted_req): 
2023-04-05 17:50:13,012 INFO     Data received from DU (dl_buffer [bytes], tx_brate downlink [Mbps], ratio_granted_req): 
2023-04-05 17:50:13,012 INFO     [[[1.08900e-07 9.99261e-01 2.52000e+02]
  [6.39800e-07 8.80064e-01 9.98000e+02]
  [1.18900e-07 9.78474e-01 7.31000e+02]
  [1.43300e-07 9.64273e-01 4.30000e+01]
  [3.19800e-07 9.09687e-01 4.76000e+02]
  [0.00000e+00 9.60960e-01 6.39000e+02]
  [4.25000e-08 9.78336e-01 7.22000e+02]
  [2.09000e-08 9.76448e-01 3.77000e+02]
  [9.28800e-07 

1/1 [==============================] - 0s 14ms/step


2023-04-05 17:50:13,052 INFO     Slice 0: Action is 1 Reward is: 0.9332451
2023-04-05 17:50:13,052 INFO     Slice 0: Action is 1 Reward is: 0.9332451
2023-04-05 17:50:13,053 INFO     Testing iteration 1
2023-04-05 17:50:13,053 INFO     Testing iteration 1
2023-04-05 17:50:13,054 INFO     Data received from DU (dl_buffer [bytes], tx_brate downlink [Mbps], ratio_granted_req): 
2023-04-05 17:50:13,054 INFO     Data received from DU (dl_buffer [bytes], tx_brate downlink [Mbps], ratio_granted_req): 
2023-04-05 17:50:13,055 INFO     [[[0.00000e+00 2.70080e-02 4.30000e+01]
  [0.00000e+00 2.79680e-02 1.38000e+02]
  [0.00000e+00 4.26345e-02 1.13000e+02]
  [2.14000e-08 4.33735e-02 3.49000e+02]
  [0.00000e+00 3.18720e-02 1.09000e+02]
  [0.00000e+00 2.69760e-02 6.20000e+01]
  [5.70000e-09 4.80000e-02 2.57000e+02]
  [0.00000e+00 1.59360e-02 2.80000e+01]
  [6.50000e-09 2.50602e-02 5.22000e+02]
  [0.00000e+00 4.37120e-02 7.80000e+01]]]
2023-04-05 17:50:13,055 INFO     [[[0.00000e+00 2.70080e-02 4.300

1/1 [==============================] - 0s 18ms/step


2023-04-05 17:50:13,105 INFO     Slice 1: Action is 1 Reward is: 0.03325402
2023-04-05 17:50:13,105 INFO     Slice 1: Action is 1 Reward is: 0.03325402
2023-04-05 17:50:13,107 INFO     Testing iteration 2
2023-04-05 17:50:13,107 INFO     Testing iteration 2
2023-04-05 17:50:13,108 INFO     Data received from DU (dl_buffer [bytes], tx_brate downlink [Mbps], ratio_granted_req): 
2023-04-05 17:50:13,108 INFO     Data received from DU (dl_buffer [bytes], tx_brate downlink [Mbps], ratio_granted_req): 
2023-04-05 17:50:13,109 INFO     [[[0.00000e+00 5.15200e-03 8.00000e+00]
  [0.00000e+00 2.13440e-02 5.40000e+01]
  [0.00000e+00 1.06240e-02 4.00000e+00]
  [0.00000e+00 5.31200e-03 4.00000e+00]
  [0.00000e+00 1.58720e-02 8.00000e+00]
  [0.00000e+00 5.33333e-03 4.00000e+00]
  [0.00000e+00 1.06240e-02 3.60000e+01]
  [0.00000e+00 1.34720e-02 1.09000e+02]
  [0.00000e+00 2.67631e-02 3.60000e+01]
  [0.00000e+00 1.06560e-02 8.00000e+00]]]
2023-04-05 17:50:13,109 INFO     [[[0.00000e+00 5.15200e-03 8.0

1/1 [==============================] - 0s 14ms/step


2023-04-05 17:50:13,151 INFO     Slice 2: Action is 2 Reward is: 27.1
2023-04-05 17:50:13,151 INFO     Slice 2: Action is 2 Reward is: 27.1
2023-04-05 17:50:13,152 INFO     Sending this message to the DU: 1,1,2
2023-04-05 17:50:13,152 INFO     Sending this message to the DU: 1,1,2
2023-04-05 17:50:23,158 INFO     Testing iteration 0
2023-04-05 17:50:23,158 INFO     Testing iteration 0
2023-04-05 17:50:23,159 INFO     Data received from DU (dl_buffer [bytes], tx_brate downlink [Mbps], ratio_granted_req): 
2023-04-05 17:50:23,159 INFO     Data received from DU (dl_buffer [bytes], tx_brate downlink [Mbps], ratio_granted_req): 
2023-04-05 17:50:23,161 INFO     [[[3.31600e-07 1.07965e+00 6.90000e+01]
  [1.27700e-07 9.80787e-01 3.15000e+02]
  [1.48400e-07 9.92896e-01 4.45000e+02]
  [1.43300e-07 9.64544e-01 8.15000e+02]
  [5.86500e-07 9.64192e-01 4.23000e+02]
  [4.25000e-08 1.03456e+00 3.02000e+02]
  [0.00000e+00 1.16720e+00 4.52000e+02]
  [4.25000e-08 9.80691e-01 7.34000e+02]
  [1.14500e-07 

1/1 [==============================] - 0s 15ms/step


2023-04-05 17:50:23,204 INFO     Slice 0: Action is 1 Reward is: 1.0114536
2023-04-05 17:50:23,204 INFO     Slice 0: Action is 1 Reward is: 1.0114536
2023-04-05 17:50:23,205 INFO     Testing iteration 1
2023-04-05 17:50:23,205 INFO     Testing iteration 1
2023-04-05 17:50:23,206 INFO     Data received from DU (dl_buffer [bytes], tx_brate downlink [Mbps], ratio_granted_req): 
2023-04-05 17:50:23,206 INFO     Data received from DU (dl_buffer [bytes], tx_brate downlink [Mbps], ratio_granted_req): 
2023-04-05 17:50:23,207 INFO     [[[0.00000e+00 4.79036e-02 6.50000e+01]
  [0.00000e+00 6.10560e-02 5.50000e+01]
  [1.58000e-08 4.35984e-02 2.96000e+02]
  [0.00000e+00 4.85120e-02 9.20000e+01]
  [2.61000e-08 4.22720e-02 1.28400e+03]
  [0.00000e+00 4.27952e-02 9.20000e+01]
  [0.00000e+00 2.95040e-02 3.90000e+01]
  [1.58000e-08 2.37108e-02 1.19000e+02]
  [0.00000e+00 3.03293e-02 5.30000e+01]
  [1.58000e-08 1.12320e-02 5.00000e+00]]]
2023-04-05 17:50:23,207 INFO     [[[0.00000e+00 4.79036e-02 6.500

1/1 [==============================] - 0s 15ms/step


2023-04-05 17:50:23,250 INFO     Slice 1: Action is 1 Reward is: 0.03809133
2023-04-05 17:50:23,250 INFO     Slice 1: Action is 1 Reward is: 0.03809133
2023-04-05 17:50:23,251 INFO     Testing iteration 2
2023-04-05 17:50:23,251 INFO     Testing iteration 2
2023-04-05 17:50:23,252 INFO     Data received from DU (dl_buffer [bytes], tx_brate downlink [Mbps], ratio_granted_req): 
2023-04-05 17:50:23,252 INFO     Data received from DU (dl_buffer [bytes], tx_brate downlink [Mbps], ratio_granted_req): 
2023-04-05 17:50:23,253 INFO     [[[0.00000e+00 1.61280e-02 1.00000e+01]
  [0.00000e+00 2.77760e-02 2.41000e+02]
  [0.00000e+00 1.62249e-02 1.20000e+01]
  [0.00000e+00 5.44000e-03 6.00000e+00]
  [0.00000e+00 1.15840e-02 1.10000e+01]
  [0.00000e+00 5.85600e-03 1.60000e+01]
  [0.00000e+00 5.33333e-03 4.00000e+00]
  [0.00000e+00 5.31200e-03 4.00000e+00]
  [0.00000e+00 1.61928e-02 8.00000e+00]
  [0.00000e+00 5.44000e-03 9.00000e+00]]]
2023-04-05 17:50:23,253 INFO     [[[0.00000e+00 1.61280e-02 1.0

1/1 [==============================] - 0s 15ms/step


2023-04-05 17:50:23,295 INFO     Slice 2: Action is 1 Reward is: 32.1
2023-04-05 17:50:23,295 INFO     Slice 2: Action is 1 Reward is: 32.1
2023-04-05 17:50:23,297 INFO     Sending this message to the DU: 1,1,1
2023-04-05 17:50:23,297 INFO     Sending this message to the DU: 1,1,1
2023-04-05 17:50:33,303 INFO     Testing iteration 0
2023-04-05 17:50:33,303 INFO     Testing iteration 0
2023-04-05 17:50:33,304 INFO     Data received from DU (dl_buffer [bytes], tx_brate downlink [Mbps], ratio_granted_req): 
2023-04-05 17:50:33,304 INFO     Data received from DU (dl_buffer [bytes], tx_brate downlink [Mbps], ratio_granted_req): 
2023-04-05 17:50:33,305 INFO     [[[0.00000e+00 9.70816e-01 3.59000e+02]
  [1.14500e-07 9.78976e-01 7.07000e+02]
  [0.00000e+00 1.14208e+00 4.95000e+02]
  [0.00000e+00 1.05891e+00 1.63000e+02]
  [6.84000e-07 9.10208e-01 9.90000e+01]
  [0.00000e+00 1.12675e+00 2.66000e+02]
  [3.45000e-08 9.78752e-01 6.77000e+02]
  [1.50800e-07 9.46859e-01 4.83000e+02]
  [4.10000e-09 

1/1 [==============================] - 0s 14ms/step


2023-04-05 17:50:33,345 INFO     Slice 0: Action is 1 Reward is: 1.0039349
2023-04-05 17:50:33,345 INFO     Slice 0: Action is 1 Reward is: 1.0039349
2023-04-05 17:50:33,346 INFO     Testing iteration 1
2023-04-05 17:50:33,346 INFO     Testing iteration 1
2023-04-05 17:50:33,347 INFO     Data received from DU (dl_buffer [bytes], tx_brate downlink [Mbps], ratio_granted_req): 
2023-04-05 17:50:33,347 INFO     Data received from DU (dl_buffer [bytes], tx_brate downlink [Mbps], ratio_granted_req): 
2023-04-05 17:50:33,348 INFO     [[[0.00000e+00 4.89639e-02 2.68000e+02]
  [0.00000e+00 3.41526e-02 2.27000e+02]
  [4.00000e-10 7.12320e-02 5.50000e+01]
  [0.00000e+00 5.85382e-02 1.21000e+02]
  [1.40000e-08 6.52851e-02 1.03000e+02]
  [0.00000e+00 6.38072e-02 1.98000e+02]
  [7.00000e-09 3.52960e-02 2.66000e+02]
  [0.00000e+00 4.81920e-02 7.30000e+01]
  [0.00000e+00 1.60960e-02 6.30000e+01]
  [0.00000e+00 2.71680e-02 4.30000e+01]]]
2023-04-05 17:50:33,348 INFO     [[[0.00000e+00 4.89639e-02 2.680

1/1 [==============================] - 0s 15ms/step


2023-04-05 17:50:33,392 INFO     Slice 1: Action is 1 Reward is: 0.0468731
2023-04-05 17:50:33,392 INFO     Slice 1: Action is 1 Reward is: 0.0468731
2023-04-05 17:50:33,393 INFO     Testing iteration 2
2023-04-05 17:50:33,393 INFO     Testing iteration 2
2023-04-05 17:50:33,394 INFO     Data received from DU (dl_buffer [bytes], tx_brate downlink [Mbps], ratio_granted_req): 
2023-04-05 17:50:33,394 INFO     Data received from DU (dl_buffer [bytes], tx_brate downlink [Mbps], ratio_granted_req): 
2023-04-05 17:50:33,395 INFO     [[[0.00000e+00 1.39116e-02 1.72000e+02]
  [0.00000e+00 1.58400e-02 1.90000e+01]
  [0.00000e+00 1.58394e-02 2.00000e+00]
  [0.00000e+00 6.62400e-03 7.50000e+01]
  [0.00000e+00 1.54560e-02 1.20000e+01]
  [0.00000e+00 2.77120e-02 8.60000e+01]
  [0.00000e+00 5.44000e-03 6.00000e+00]
  [0.00000e+00 2.13976e-02 2.10000e+01]
  [0.00000e+00 1.05920e-02 4.00000e+00]
  [0.00000e+00 1.99360e-02 2.10000e+02]]]
2023-04-05 17:50:33,395 INFO     [[[0.00000e+00 1.39116e-02 1.720

1/1 [==============================] - 0s 16ms/step


2023-04-05 17:50:33,440 INFO     Slice 2: Action is 1 Reward is: 60.7
2023-04-05 17:50:33,440 INFO     Slice 2: Action is 1 Reward is: 60.7
2023-04-05 17:50:33,442 INFO     Sending this message to the DU: 1,1,1
2023-04-05 17:50:33,442 INFO     Sending this message to the DU: 1,1,1
2023-04-05 17:50:43,449 INFO     Testing iteration 0
2023-04-05 17:50:43,449 INFO     Testing iteration 0
2023-04-05 17:50:43,451 INFO     Data received from DU (dl_buffer [bytes], tx_brate downlink [Mbps], ratio_granted_req): 
2023-04-05 17:50:43,451 INFO     Data received from DU (dl_buffer [bytes], tx_brate downlink [Mbps], ratio_granted_req): 
2023-04-05 17:50:43,451 INFO     [[[2.09000e-07 9.65783e-01 3.71000e+02]
  [0.00000e+00 9.76512e-01 6.17000e+02]
  [6.97000e-08 9.84578e-01 7.54000e+02]
  [8.89000e-08 1.32525e+00 2.88000e+02]
  [0.00000e+00 9.80627e-01 4.93000e+02]
  [2.18800e-07 9.38496e-01 1.07700e+03]
  [5.69000e-08 1.03600e+00 7.57000e+02]
  [0.00000e+00 9.79616e-01 7.04000e+02]
  [1.78700e-07 

1/1 [==============================] - 0s 15ms/step


2023-04-05 17:50:43,491 INFO     Slice 0: Action is 1 Reward is: 1.0163949
2023-04-05 17:50:43,491 INFO     Slice 0: Action is 1 Reward is: 1.0163949
2023-04-05 17:50:43,492 INFO     Testing iteration 1
2023-04-05 17:50:43,492 INFO     Testing iteration 1
2023-04-05 17:50:43,493 INFO     Data received from DU (dl_buffer [bytes], tx_brate downlink [Mbps], ratio_granted_req): 
2023-04-05 17:50:43,493 INFO     Data received from DU (dl_buffer [bytes], tx_brate downlink [Mbps], ratio_granted_req): 
2023-04-05 17:50:43,493 INFO     [[[0.00000e+00 8.46265e-02 1.57000e+02]
  [0.00000e+00 3.74720e-02 5.80000e+01]
  [0.00000e+00 3.72369e-02 1.86000e+02]
  [0.00000e+00 4.27520e-02 9.90000e+01]
  [0.00000e+00 6.34560e-02 3.47000e+02]
  [0.00000e+00 6.68160e-02 4.77000e+02]
  [9.70000e-09 3.18394e-02 5.10000e+01]
  [0.00000e+00 4.36948e-02 4.20000e+01]
  [4.08000e-08 2.44160e-02 4.00000e+00]
  [0.00000e+00 2.11520e-02 6.40000e+01]]]
2023-04-05 17:50:43,493 INFO     [[[0.00000e+00 8.46265e-02 1.570

1/1 [==============================] - 0s 15ms/step


2023-04-05 17:50:43,540 INFO     Slice 1: Action is 1 Reward is: 0.04534616
2023-04-05 17:50:43,540 INFO     Slice 1: Action is 1 Reward is: 0.04534616
2023-04-05 17:50:43,541 INFO     Testing iteration 2
2023-04-05 17:50:43,541 INFO     Testing iteration 2
2023-04-05 17:50:43,542 INFO     Data received from DU (dl_buffer [bytes], tx_brate downlink [Mbps], ratio_granted_req): 
2023-04-05 17:50:43,542 INFO     Data received from DU (dl_buffer [bytes], tx_brate downlink [Mbps], ratio_granted_req): 
2023-04-05 17:50:43,544 INFO     [[[1.21000e-08 2.26560e-02 1.41000e+02]
  [0.00000e+00 1.59360e-02 1.20000e+01]
  [0.00000e+00 1.20640e-02 1.14000e+02]
  [0.00000e+00 2.21044e-02 7.80000e+01]
  [0.00000e+00 5.37600e-03 5.00000e+00]
  [0.00000e+00 2.63775e-02 1.90000e+01]
  [0.00000e+00 1.07952e-02 2.10000e+01]
  [0.00000e+00 2.14618e-02 2.50000e+01]
  [1.51000e-08 2.68916e-02 3.10000e+02]
  [0.00000e+00 2.25920e-02 2.80000e+01]]]
2023-04-05 17:50:43,544 INFO     [[[1.21000e-08 2.26560e-02 1.4

1/1 [==============================] - 0s 14ms/step


2023-04-05 17:50:43,583 INFO     Slice 2: Action is 1 Reward is: 75.3
2023-04-05 17:50:43,583 INFO     Slice 2: Action is 1 Reward is: 75.3
2023-04-05 17:50:43,584 INFO     Sending this message to the DU: 1,1,1
2023-04-05 17:50:43,584 INFO     Sending this message to the DU: 1,1,1
2023-04-05 17:50:53,592 INFO     Testing iteration 0
2023-04-05 17:50:53,592 INFO     Testing iteration 0
2023-04-05 17:50:53,593 INFO     Data received from DU (dl_buffer [bytes], tx_brate downlink [Mbps], ratio_granted_req): 
2023-04-05 17:50:53,593 INFO     Data received from DU (dl_buffer [bytes], tx_brate downlink [Mbps], ratio_granted_req): 
2023-04-05 17:50:53,594 INFO     [[[1.43300e-07 1.26934e+00 4.40000e+02]
  [6.87000e-08 9.74008e-01 6.66000e+02]
  [5.82700e-07 8.36224e-01 2.57000e+02]
  [3.16000e-08 1.01831e+00 1.83000e+02]
  [5.57300e-07 1.28360e+00 1.27000e+02]
  [0.00000e+00 9.65152e-01 7.94000e+02]
  [0.00000e+00 1.06090e+00 4.22000e+02]
  [3.42500e-07 9.08369e-01 4.92000e+02]
  [6.81000e-08 

1/1 [==============================] - 0s 16ms/step


2023-04-05 17:50:53,641 INFO     Slice 0: Action is 1 Reward is: 1.0257087
2023-04-05 17:50:53,641 INFO     Slice 0: Action is 1 Reward is: 1.0257087
2023-04-05 17:50:53,642 INFO     Testing iteration 1
2023-04-05 17:50:53,642 INFO     Testing iteration 1
2023-04-05 17:50:53,643 INFO     Data received from DU (dl_buffer [bytes], tx_brate downlink [Mbps], ratio_granted_req): 
2023-04-05 17:50:53,643 INFO     Data received from DU (dl_buffer [bytes], tx_brate downlink [Mbps], ratio_granted_req): 
2023-04-05 17:50:53,644 INFO     [[[0.00000e+00 2.75840e-02 4.70000e+01]
  [0.00000e+00 2.51245e-02 9.30000e+01]
  [0.00000e+00 5.49120e-02 5.80000e+01]
  [0.00000e+00 3.75261e-02 6.20000e+01]
  [0.00000e+00 4.80960e-02 1.86000e+02]
  [0.00000e+00 2.69440e-02 1.01000e+02]
  [5.40000e-09 5.04320e-02 5.64000e+02]
  [3.15000e-08 2.71680e-02 9.00000e+00]
  [1.58000e-08 7.68835e-02 2.78000e+02]
  [0.00000e+00 2.47360e-02 6.10000e+01]]]
2023-04-05 17:50:53,644 INFO     [[[0.00000e+00 2.75840e-02 4.700

1/1 [==============================] - 0s 15ms/step


2023-04-05 17:50:53,688 INFO     Slice 1: Action is 1 Reward is: 0.03994061
2023-04-05 17:50:53,688 INFO     Slice 1: Action is 1 Reward is: 0.03994061
2023-04-05 17:50:53,689 INFO     Testing iteration 2
2023-04-05 17:50:53,689 INFO     Testing iteration 2
2023-04-05 17:50:53,690 INFO     Data received from DU (dl_buffer [bytes], tx_brate downlink [Mbps], ratio_granted_req): 
2023-04-05 17:50:53,690 INFO     Data received from DU (dl_buffer [bytes], tx_brate downlink [Mbps], ratio_granted_req): 
2023-04-05 17:50:53,691 INFO     [[[0.00000e+00 2.62720e-02 3.20000e+01]
  [0.00000e+00 2.66667e-02 2.40000e+01]
  [0.00000e+00 1.04640e-02 2.00000e+01]
  [0.00000e+00 2.12800e-02 2.90000e+01]
  [0.00000e+00 1.65120e-02 5.00000e+00]
  [0.00000e+00 1.03040e-02 8.00000e+00]
  [0.00000e+00 1.06988e-02 8.00000e+00]
  [0.00000e+00 1.19360e-02 9.10000e+01]
  [0.00000e+00 6.90763e-03 5.50000e+01]
  [0.00000e+00 2.14297e-02 1.50000e+01]]]
2023-04-05 17:50:53,691 INFO     [[[0.00000e+00 2.62720e-02 3.2

1/1 [==============================] - 0s 16ms/step


2023-04-05 17:50:53,737 INFO     Slice 2: Action is 1 Reward is: 28.7
2023-04-05 17:50:53,737 INFO     Slice 2: Action is 1 Reward is: 28.7
2023-04-05 17:50:53,739 INFO     Sending this message to the DU: 1,1,1
2023-04-05 17:50:53,739 INFO     Sending this message to the DU: 1,1,1
2023-04-05 17:51:03,746 INFO     Testing iteration 0
2023-04-05 17:51:03,746 INFO     Testing iteration 0
2023-04-05 17:51:03,748 INFO     Data received from DU (dl_buffer [bytes], tx_brate downlink [Mbps], ratio_granted_req): 
2023-04-05 17:51:03,748 INFO     Data received from DU (dl_buffer [bytes], tx_brate downlink [Mbps], ratio_granted_req): 
2023-04-05 17:51:03,749 INFO     [[[7.56000e-08 9.92352e-01 7.43000e+02]
  [8.89000e-08 1.01418e+00 8.26000e+02]
  [1.38800e-07 9.40992e-01 6.21000e+02]
  [1.34300e-07 1.07672e+00 4.52000e+02]
  [0.00000e+00 9.93408e-01 5.60000e+02]
  [6.70900e-07 7.87020e-01 1.61000e+02]
  [0.00000e+00 9.81856e-01 5.38000e+02]
  [8.09000e-08 1.00477e+00 1.61000e+02]
  [3.45000e-08 

1/1 [==============================] - 0s 14ms/step


2023-04-05 17:51:03,790 INFO     Slice 0: Action is 1 Reward is: 0.9525567
2023-04-05 17:51:03,790 INFO     Slice 0: Action is 1 Reward is: 0.9525567
2023-04-05 17:51:03,791 INFO     Testing iteration 1
2023-04-05 17:51:03,791 INFO     Testing iteration 1
2023-04-05 17:51:03,792 INFO     Data received from DU (dl_buffer [bytes], tx_brate downlink [Mbps], ratio_granted_req): 
2023-04-05 17:51:03,792 INFO     Data received from DU (dl_buffer [bytes], tx_brate downlink [Mbps], ratio_granted_req): 
2023-04-05 17:51:03,793 INFO     [[[0.00000e+00 3.71840e-02 7.00000e+01]
  [2.97000e-08 1.31840e-02 4.65000e+02]
  [0.00000e+00 3.81440e-02 2.55000e+02]
  [0.00000e+00 3.73120e-02 1.28000e+02]
  [0.00000e+00 4.23680e-02 2.40000e+01]
  [0.00000e+00 3.16800e-02 2.40000e+01]
  [0.00000e+00 6.87680e-02 1.69000e+02]
  [0.00000e+00 5.19518e-02 9.60000e+01]
  [4.28000e-08 4.56320e-02 1.19000e+02]
  [0.00000e+00 3.46880e-02 6.50000e+01]]]
2023-04-05 17:51:03,793 INFO     [[[0.00000e+00 3.71840e-02 7.000

1/1 [==============================] - 0s 14ms/step


2023-04-05 17:51:03,835 INFO     Slice 1: Action is 1 Reward is: 0.04009118
2023-04-05 17:51:03,835 INFO     Slice 1: Action is 1 Reward is: 0.04009118
2023-04-05 17:51:03,836 INFO     Testing iteration 2
2023-04-05 17:51:03,836 INFO     Testing iteration 2
2023-04-05 17:51:03,837 INFO     Data received from DU (dl_buffer [bytes], tx_brate downlink [Mbps], ratio_granted_req): 
2023-04-05 17:51:03,837 INFO     Data received from DU (dl_buffer [bytes], tx_brate downlink [Mbps], ratio_granted_req): 
2023-04-05 17:51:03,838 INFO     [[[0.00000e+00 1.05600e-02 8.00000e+00]
  [0.00000e+00 1.80562e-02 4.50000e+01]
  [0.00000e+00 1.06880e-02 1.30000e+01]
  [0.00000e+00 2.12480e-02 3.00000e+01]
  [0.00000e+00 2.17510e-02 2.50000e+01]
  [0.00000e+00 5.33333e-03 4.00000e+00]
  [0.00000e+00 1.40160e-02 1.69000e+02]
  [0.00000e+00 1.04640e-02 1.10000e+01]
  [0.00000e+00 2.14940e-02 1.60000e+01]
  [0.00000e+00 1.77349e-02 7.20000e+01]]]
2023-04-05 17:51:03,838 INFO     [[[0.00000e+00 1.05600e-02 8.0

1/1 [==============================] - 0s 14ms/step


2023-04-05 17:51:03,877 INFO     Slice 2: Action is 2 Reward is: 39.3
2023-04-05 17:51:03,877 INFO     Slice 2: Action is 2 Reward is: 39.3
2023-04-05 17:51:03,878 INFO     Sending this message to the DU: 1,1,2
2023-04-05 17:51:03,878 INFO     Sending this message to the DU: 1,1,2
2023-04-05 17:51:13,885 INFO     Testing iteration 0
2023-04-05 17:51:13,885 INFO     Testing iteration 0
2023-04-05 17:51:13,886 INFO     Data received from DU (dl_buffer [bytes], tx_brate downlink [Mbps], ratio_granted_req): 
2023-04-05 17:51:13,886 INFO     Data received from DU (dl_buffer [bytes], tx_brate downlink [Mbps], ratio_granted_req): 
2023-04-05 17:51:13,887 INFO     [[[4.17300e-07 8.12256e-01 1.12000e+02]
  [1.43300e-07 1.20774e+00 2.63000e+02]
  [0.00000e+00 1.00205e+00 4.21000e+02]
  [8.89000e-08 1.08925e+00 6.96000e+02]
  [0.00000e+00 1.00998e+00 6.65000e+02]
  [3.45000e-08 9.87744e-01 3.19000e+02]
  [8.33800e-07 8.45120e-01 4.26000e+02]
  [4.01100e-07 9.07680e-01 2.64000e+02]
  [1.56100e-07 

1/1 [==============================] - 0s 14ms/step


2023-04-05 17:51:13,927 INFO     Slice 0: Action is 1 Reward is: 0.9818196
2023-04-05 17:51:13,927 INFO     Slice 0: Action is 1 Reward is: 0.9818196
2023-04-05 17:51:13,928 INFO     Testing iteration 1
2023-04-05 17:51:13,928 INFO     Testing iteration 1
2023-04-05 17:51:13,930 INFO     Data received from DU (dl_buffer [bytes], tx_brate downlink [Mbps], ratio_granted_req): 
2023-04-05 17:51:13,930 INFO     Data received from DU (dl_buffer [bytes], tx_brate downlink [Mbps], ratio_granted_req): 
2023-04-05 17:51:13,930 INFO     [[[0.00000e+00 4.13494e-02 5.50000e+01]
  [1.58000e-08 1.83454e-02 1.93000e+02]
  [0.00000e+00 4.30720e-02 7.80000e+01]
  [0.00000e+00 3.18720e-02 8.90000e+01]
  [0.00000e+00 5.30240e-02 7.90000e+01]
  [0.00000e+00 3.71084e-02 2.30000e+01]
  [0.00000e+00 5.32480e-02 7.70000e+01]
  [3.15000e-08 3.20321e-02 6.10000e+01]
  [0.00000e+00 4.18560e-02 4.43000e+02]
  [0.00000e+00 4.97920e-02 4.90000e+01]]]
2023-04-05 17:51:13,930 INFO     [[[0.00000e+00 4.13494e-02 5.500

1/1 [==============================] - 0s 16ms/step


2023-04-05 17:51:13,971 INFO     Slice 1: Action is 1 Reward is: 0.04016993
2023-04-05 17:51:13,971 INFO     Slice 1: Action is 1 Reward is: 0.04016993
2023-04-05 17:51:13,972 INFO     Testing iteration 2
2023-04-05 17:51:13,972 INFO     Testing iteration 2
2023-04-05 17:51:13,973 INFO     Data received from DU (dl_buffer [bytes], tx_brate downlink [Mbps], ratio_granted_req): 
2023-04-05 17:51:13,973 INFO     Data received from DU (dl_buffer [bytes], tx_brate downlink [Mbps], ratio_granted_req): 
2023-04-05 17:51:13,974 INFO     [[[0.00000e+00 2.66880e-02 2.60000e+01]
  [2.03000e-08 8.48000e-03 1.01000e+02]
  [0.00000e+00 2.12691e-02 1.30000e+01]
  [0.00000e+00 1.06667e-02 7.00000e+00]
  [0.00000e+00 1.68996e-02 4.80000e+01]
  [0.00000e+00 5.30120e-03 4.00000e+00]
  [0.00000e+00 1.08480e-02 1.30000e+01]
  [0.00000e+00 1.60643e-02 1.60000e+01]
  [0.00000e+00 1.59360e-02 2.10000e+01]
  [0.00000e+00 2.13012e-02 1.80000e+01]]]
2023-04-05 17:51:13,974 INFO     [[[0.00000e+00 2.66880e-02 2.6

1/1 [==============================] - 0s 13ms/step


2023-04-05 17:51:14,014 INFO     Slice 2: Action is 1 Reward is: 26.7
2023-04-05 17:51:14,014 INFO     Slice 2: Action is 1 Reward is: 26.7
2023-04-05 17:51:14,015 INFO     Sending this message to the DU: 1,1,1
2023-04-05 17:51:14,015 INFO     Sending this message to the DU: 1,1,1
2023-04-05 17:51:24,023 INFO     Testing iteration 0
2023-04-05 17:51:24,023 INFO     Testing iteration 0
2023-04-05 17:51:24,024 INFO     Data received from DU (dl_buffer [bytes], tx_brate downlink [Mbps], ratio_granted_req): 
2023-04-05 17:51:24,024 INFO     Data received from DU (dl_buffer [bytes], tx_brate downlink [Mbps], ratio_granted_req): 
2023-04-05 17:51:24,025 INFO     [[[9.69000e-08 9.78816e-01 3.10000e+01]
  [4.25000e-08 9.80048e-01 6.87000e+02]
  [4.25000e-08 9.83648e-01 7.36000e+02]
  [0.00000e+00 9.77184e-01 5.07000e+02]
  [2.44400e-07 9.54731e-01 3.84000e+02]
  [2.62900e-07 8.79261e-01 8.09000e+02]
  [0.00000e+00 1.00129e+00 6.91000e+02]
  [3.21300e-07 8.65504e-01 2.03000e+02]
  [7.37000e-08 

1/1 [==============================] - 0s 15ms/step


2023-04-05 17:51:24,068 INFO     Slice 0: Action is 1 Reward is: 0.9870048
2023-04-05 17:51:24,068 INFO     Slice 0: Action is 1 Reward is: 0.9870048
2023-04-05 17:51:24,069 INFO     Testing iteration 1
2023-04-05 17:51:24,069 INFO     Testing iteration 1
2023-04-05 17:51:24,070 INFO     Data received from DU (dl_buffer [bytes], tx_brate downlink [Mbps], ratio_granted_req): 
2023-04-05 17:51:24,070 INFO     Data received from DU (dl_buffer [bytes], tx_brate downlink [Mbps], ratio_granted_req): 
2023-04-05 17:51:24,072 INFO     [[[0.00000e+00 2.66880e-02 1.02000e+02]
  [0.00000e+00 2.86908e-02 1.30000e+02]
  [0.00000e+00 4.29558e-02 4.60000e+01]
  [0.00000e+00 3.96800e-02 2.10000e+01]
  [0.00000e+00 6.39360e-02 1.22000e+02]
  [6.28000e-08 2.67952e-02 4.90000e+01]
  [0.00000e+00 2.68594e-02 8.90000e+01]
  [0.00000e+00 5.36867e-02 1.48000e+02]
  [1.58000e-08 5.40480e-02 7.00000e+01]
  [6.28000e-08 4.26560e-02 1.53000e+02]]]
2023-04-05 17:51:24,072 INFO     [[[0.00000e+00 2.66880e-02 1.020

1/1 [==============================] - 0s 13ms/step


2023-04-05 17:51:24,113 INFO     Slice 1: Action is 1 Reward is: 0.04059959
2023-04-05 17:51:24,113 INFO     Slice 1: Action is 1 Reward is: 0.04059959
2023-04-05 17:51:24,114 INFO     Testing iteration 2
2023-04-05 17:51:24,114 INFO     Testing iteration 2
2023-04-05 17:51:24,115 INFO     Data received from DU (dl_buffer [bytes], tx_brate downlink [Mbps], ratio_granted_req): 
2023-04-05 17:51:24,115 INFO     Data received from DU (dl_buffer [bytes], tx_brate downlink [Mbps], ratio_granted_req): 
2023-04-05 17:51:24,116 INFO     [[[0.00000e+00 2.15680e-02 4.00000e+01]
  [0.00000e+00 1.62880e-02 2.70000e+01]
  [0.00000e+00 1.58720e-02 1.70000e+01]
  [0.00000e+00 1.11486e-02 3.30000e+01]
  [0.00000e+00 1.63200e-02 8.50000e+01]
  [0.00000e+00 1.05920e-02 1.30000e+01]
  [0.00000e+00 1.58080e-02 1.90000e+01]
  [0.00000e+00 2.65600e-02 1.30000e+01]
  [0.00000e+00 1.05920e-02 8.00000e+00]
  [3.20000e-09 2.68480e-02 4.80000e+01]]]
2023-04-05 17:51:24,116 INFO     [[[0.00000e+00 2.15680e-02 4.0

1/1 [==============================] - 0s 14ms/step


2023-04-05 17:51:24,154 INFO     Slice 2: Action is 1 Reward is: 30.3
2023-04-05 17:51:24,154 INFO     Slice 2: Action is 1 Reward is: 30.3
2023-04-05 17:51:24,155 INFO     Sending this message to the DU: 1,1,1
2023-04-05 17:51:24,155 INFO     Sending this message to the DU: 1,1,1
2023-04-05 17:51:34,162 INFO     Testing iteration 0
2023-04-05 17:51:34,162 INFO     Testing iteration 0
2023-04-05 17:51:34,163 INFO     Data received from DU (dl_buffer [bytes], tx_brate downlink [Mbps], ratio_granted_req): 
2023-04-05 17:51:34,163 INFO     Data received from DU (dl_buffer [bytes], tx_brate downlink [Mbps], ratio_granted_req): 
2023-04-05 17:51:34,164 INFO     [[[5.46000e-08 9.96112e-01 1.03100e+03]
  [5.05000e-08 9.82104e-01 4.55000e+02]
  [4.01000e-08 1.01680e+00 5.46000e+02]
  [1.43300e-07 9.80128e-01 7.02000e+02]
  [8.89000e-08 1.03670e+00 3.61000e+02]
  [1.60600e-07 9.52928e-01 7.01000e+02]
  [9.69000e-08 1.07856e+00 5.55000e+02]
  [8.89000e-08 1.00074e+00 7.56000e+02]
  [0.00000e+00 

1/1 [==============================] - 0s 15ms/step


2023-04-05 17:51:34,205 INFO     Slice 0: Action is 1 Reward is: 1.0323342
2023-04-05 17:51:34,205 INFO     Slice 0: Action is 1 Reward is: 1.0323342
2023-04-05 17:51:34,207 INFO     Testing iteration 1
2023-04-05 17:51:34,207 INFO     Testing iteration 1
2023-04-05 17:51:34,208 INFO     Data received from DU (dl_buffer [bytes], tx_brate downlink [Mbps], ratio_granted_req): 
2023-04-05 17:51:34,208 INFO     Data received from DU (dl_buffer [bytes], tx_brate downlink [Mbps], ratio_granted_req): 
2023-04-05 17:51:34,209 INFO     [[[0.00000e+00 2.24320e-02 7.00000e+01]
  [0.00000e+00 1.07840e-02 1.30000e+01]
  [0.00000e+00 6.84659e-02 6.40000e+01]
  [0.00000e+00 1.59679e-02 4.60000e+01]
  [0.00000e+00 3.70560e-02 6.00000e+01]
  [0.00000e+00 3.72800e-02 7.50000e+01]
  [0.00000e+00 3.26400e-02 1.25000e+02]
  [0.00000e+00 3.20321e-02 8.10000e+01]
  [0.00000e+00 5.21600e-02 1.45000e+02]
  [0.00000e+00 4.27520e-02 6.50000e+01]]]
2023-04-05 17:51:34,209 INFO     [[[0.00000e+00 2.24320e-02 7.000

1/1 [==============================] - 0s 15ms/step


2023-04-05 17:51:34,254 INFO     Slice 1: Action is 1 Reward is: 0.03515699
2023-04-05 17:51:34,254 INFO     Slice 1: Action is 1 Reward is: 0.03515699
2023-04-05 17:51:34,255 INFO     Testing iteration 2
2023-04-05 17:51:34,255 INFO     Testing iteration 2
2023-04-05 17:51:34,256 INFO     Data received from DU (dl_buffer [bytes], tx_brate downlink [Mbps], ratio_granted_req): 
2023-04-05 17:51:34,256 INFO     Data received from DU (dl_buffer [bytes], tx_brate downlink [Mbps], ratio_granted_req): 
2023-04-05 17:51:34,257 INFO     [[[0.00000e+00 1.06667e-02 8.00000e+00]
  [0.00000e+00 3.61920e-02 1.24000e+02]
  [1.47000e-08 1.57760e-02 1.90000e+01]
  [0.00000e+00 2.88193e-02 3.00000e+02]
  [3.10000e-09 5.31200e-03 2.30000e+01]
  [0.00000e+00 2.19200e-02 1.50000e+01]
  [0.00000e+00 2.15582e-02 2.80000e+01]
  [0.00000e+00 1.08800e-02 1.50000e+01]
  [0.00000e+00 1.08273e-02 8.00000e+00]
  [0.00000e+00 1.06667e-02 8.00000e+00]]]
2023-04-05 17:51:34,257 INFO     [[[0.00000e+00 1.06667e-02 8.0

1/1 [==============================] - 0s 15ms/step


2023-04-05 17:51:34,303 INFO     Slice 2: Action is 1 Reward is: 54.8
2023-04-05 17:51:34,303 INFO     Slice 2: Action is 1 Reward is: 54.8
2023-04-05 17:51:34,304 INFO     Sending this message to the DU: 1,1,1
2023-04-05 17:51:34,304 INFO     Sending this message to the DU: 1,1,1
2023-04-05 17:51:44,311 INFO     Testing iteration 0
2023-04-05 17:51:44,311 INFO     Testing iteration 0
2023-04-05 17:51:44,312 INFO     Data received from DU (dl_buffer [bytes], tx_brate downlink [Mbps], ratio_granted_req): 
2023-04-05 17:51:44,312 INFO     Data received from DU (dl_buffer [bytes], tx_brate downlink [Mbps], ratio_granted_req): 
2023-04-05 17:51:44,313 INFO     [[[4.13100e-07 9.06240e-01 2.06000e+02]
  [9.69000e-08 9.74400e-01 6.10000e+02]
  [8.06600e-07 7.64480e-01 4.77000e+02]
  [1.43300e-07 9.66747e-01 6.19000e+02]
  [1.08900e-07 9.72928e-01 7.62000e+02]
  [3.21000e-08 9.58240e-01 1.05500e+03]
  [2.07300e-07 9.19136e-01 5.45000e+02]
  [0.00000e+00 9.92416e-01 7.84000e+02]
  [2.21500e-07 

1/1 [==============================] - 0s 14ms/step


2023-04-05 17:51:44,353 INFO     Slice 0: Action is 1 Reward is: 0.9510207
2023-04-05 17:51:44,353 INFO     Slice 0: Action is 1 Reward is: 0.9510207
2023-04-05 17:51:44,354 INFO     Testing iteration 1
2023-04-05 17:51:44,354 INFO     Testing iteration 1
2023-04-05 17:51:44,355 INFO     Data received from DU (dl_buffer [bytes], tx_brate downlink [Mbps], ratio_granted_req): 
2023-04-05 17:51:44,355 INFO     Data received from DU (dl_buffer [bytes], tx_brate downlink [Mbps], ratio_granted_req): 
2023-04-05 17:51:44,356 INFO     [[[0.00000e+00 4.17600e-02 1.34000e+02]
  [0.00000e+00 3.83936e-02 1.26000e+02]
  [0.00000e+00 2.96960e-02 1.35000e+02]
  [0.00000e+00 4.28916e-02 7.20000e+01]
  [0.00000e+00 3.06185e-02 2.78000e+02]
  [0.00000e+00 5.31084e-02 2.84000e+02]
  [0.00000e+00 3.70880e-02 2.70000e+01]
  [2.94000e-08 3.70560e-02 4.30000e+01]
  [0.00000e+00 4.26988e-02 1.21000e+02]
  [1.58000e-08 6.22720e-02 5.14000e+02]]]
2023-04-05 17:51:44,356 INFO     [[[0.00000e+00 4.17600e-02 1.340

1/1 [==============================] - 0s 14ms/step


2023-04-05 17:51:44,396 INFO     Slice 1: Action is 1 Reward is: 0.04155829
2023-04-05 17:51:44,396 INFO     Slice 1: Action is 1 Reward is: 0.04155829
2023-04-05 17:51:44,397 INFO     Testing iteration 2
2023-04-05 17:51:44,397 INFO     Testing iteration 2
2023-04-05 17:51:44,398 INFO     Data received from DU (dl_buffer [bytes], tx_brate downlink [Mbps], ratio_granted_req): 
2023-04-05 17:51:44,398 INFO     Data received from DU (dl_buffer [bytes], tx_brate downlink [Mbps], ratio_granted_req): 
2023-04-05 17:51:44,399 INFO     [[[0.00000e+00 1.61280e-02 1.40000e+01]
  [0.00000e+00 1.06240e-02 4.00000e+00]
  [0.00000e+00 1.22880e-02 6.70000e+01]
  [0.00000e+00 5.50400e-03 8.00000e+00]
  [0.00000e+00 1.75360e-02 6.70000e+01]
  [0.00000e+00 2.38715e-02 1.15000e+02]
  [0.00000e+00 2.13440e-02 1.10000e+01]
  [0.00000e+00 1.76960e-02 6.60000e+01]
  [0.00000e+00 1.59360e-02 4.00000e+00]
  [0.00000e+00 2.10560e-02 1.00000e+01]]]
2023-04-05 17:51:44,399 INFO     [[[0.00000e+00 1.61280e-02 1.4

1/1 [==============================] - 0s 21ms/step


2023-04-05 17:51:44,451 INFO     Slice 2: Action is 1 Reward is: 36.6
2023-04-05 17:51:44,451 INFO     Slice 2: Action is 1 Reward is: 36.6
2023-04-05 17:51:44,453 INFO     Sending this message to the DU: 1,1,1
2023-04-05 17:51:44,453 INFO     Sending this message to the DU: 1,1,1
2023-04-05 17:51:54,460 INFO     Testing iteration 0
2023-04-05 17:51:54,460 INFO     Testing iteration 0
2023-04-05 17:51:54,461 INFO     Data received from DU (dl_buffer [bytes], tx_brate downlink [Mbps], ratio_granted_req): 
2023-04-05 17:51:54,461 INFO     Data received from DU (dl_buffer [bytes], tx_brate downlink [Mbps], ratio_granted_req): 
2023-04-05 17:51:54,462 INFO     [[[0.00000e+00 9.92576e-01 6.55000e+02]
  [4.40300e-07 1.03734e+00 1.30000e+02]
  [5.05000e-08 9.82329e-01 4.05000e+02]
  [0.00000e+00 9.82329e-01 7.58000e+02]
  [0.00000e+00 1.00730e+00 7.12000e+02]
  [0.00000e+00 9.65558e-01 7.54000e+02]
  [2.93900e-07 9.09141e-01 3.40000e+02]
  [2.65000e-08 1.05292e+00 4.49000e+02]
  [2.67700e-07 

1/1 [==============================] - 0s 15ms/step


2023-04-05 17:51:54,505 INFO     Slice 0: Action is 1 Reward is: 0.9915935
2023-04-05 17:51:54,505 INFO     Slice 0: Action is 1 Reward is: 0.9915935
2023-04-05 17:51:54,506 INFO     Testing iteration 1
2023-04-05 17:51:54,506 INFO     Testing iteration 1
2023-04-05 17:51:54,507 INFO     Data received from DU (dl_buffer [bytes], tx_brate downlink [Mbps], ratio_granted_req): 
2023-04-05 17:51:54,507 INFO     Data received from DU (dl_buffer [bytes], tx_brate downlink [Mbps], ratio_granted_req): 
2023-04-05 17:51:54,508 INFO     [[[0.00000e+00 4.75520e-02 1.02000e+02]
  [1.58000e-08 1.13920e-02 2.35000e+02]
  [0.00000e+00 4.82249e-02 7.90000e+01]
  [0.00000e+00 4.63293e-02 7.70000e+01]
  [0.00000e+00 4.02240e-02 3.50000e+01]
  [3.70000e-09 4.79679e-02 4.19000e+02]
  [0.00000e+00 3.47309e-02 4.80000e+01]
  [0.00000e+00 2.13333e-02 2.60000e+01]
  [0.00000e+00 4.84819e-02 1.54000e+02]
  [0.00000e+00 7.30281e-02 1.73000e+02]]]
2023-04-05 17:51:54,508 INFO     [[[0.00000e+00 4.75520e-02 1.020

1/1 [==============================] - 0s 13ms/step


2023-04-05 17:51:54,548 INFO     Slice 1: Action is 1 Reward is: 0.04192643
2023-04-05 17:51:54,548 INFO     Slice 1: Action is 1 Reward is: 0.04192643
2023-04-05 17:51:54,549 INFO     Testing iteration 2
2023-04-05 17:51:54,549 INFO     Testing iteration 2
2023-04-05 17:51:54,550 INFO     Data received from DU (dl_buffer [bytes], tx_brate downlink [Mbps], ratio_granted_req): 
2023-04-05 17:51:54,550 INFO     Data received from DU (dl_buffer [bytes], tx_brate downlink [Mbps], ratio_granted_req): 
2023-04-05 17:51:54,551 INFO     [[[0.00000e+00 1.04640e-02 1.20000e+01]
  [0.00000e+00 1.63213e-02 3.70000e+01]
  [0.00000e+00 1.06880e-02 1.00000e+01]
  [0.00000e+00 1.60640e-02 7.00000e+00]
  [0.00000e+00 1.11680e-02 1.70000e+01]
  [0.00000e+00 1.06880e-02 1.00000e+01]
  [0.00000e+00 1.58720e-02 2.10000e+01]
  [9.50000e-09 6.93976e-03 7.20000e+01]
  [0.00000e+00 1.62570e-02 6.10000e+01]
  [0.00000e+00 5.33333e-03 7.00000e+00]]]
2023-04-05 17:51:54,551 INFO     [[[0.00000e+00 1.04640e-02 1.2

1/1 [==============================] - 0s 15ms/step


2023-04-05 17:51:54,592 INFO     Slice 2: Action is 1 Reward is: 25.4
2023-04-05 17:51:54,592 INFO     Slice 2: Action is 1 Reward is: 25.4
2023-04-05 17:51:54,593 INFO     Sending this message to the DU: 1,1,1
2023-04-05 17:51:54,593 INFO     Sending this message to the DU: 1,1,1
2023-04-05 17:52:04,600 INFO     Testing iteration 0
2023-04-05 17:52:04,600 INFO     Testing iteration 0
2023-04-05 17:52:04,601 INFO     Data received from DU (dl_buffer [bytes], tx_brate downlink [Mbps], ratio_granted_req): 
2023-04-05 17:52:04,601 INFO     Data received from DU (dl_buffer [bytes], tx_brate downlink [Mbps], ratio_granted_req): 
2023-04-05 17:52:04,602 INFO     [[[0.00000e+00 9.79712e-01 6.63000e+02]
  [1.27300e-07 1.07059e+00 1.27000e+02]
  [1.38950e-06 6.27968e-01 2.16000e+02]
  [9.26900e-07 6.93880e-01 5.10000e+01]
  [0.00000e+00 9.81141e-01 7.04000e+02]
  [6.33000e-08 1.02252e+00 6.89000e+02]
  [4.25000e-08 9.66432e-01 6.70000e+02]
  [4.25000e-08 9.76832e-01 3.22000e+02]
  [5.25900e-07 

1/1 [==============================] - 0s 14ms/step


2023-04-05 17:52:04,644 INFO     Slice 0: Action is 1 Reward is: 0.9018654
2023-04-05 17:52:04,644 INFO     Slice 0: Action is 1 Reward is: 0.9018654
2023-04-05 17:52:04,645 INFO     Testing iteration 1
2023-04-05 17:52:04,645 INFO     Testing iteration 1
2023-04-05 17:52:04,646 INFO     Data received from DU (dl_buffer [bytes], tx_brate downlink [Mbps], ratio_granted_req): 
2023-04-05 17:52:04,646 INFO     Data received from DU (dl_buffer [bytes], tx_brate downlink [Mbps], ratio_granted_req): 
2023-04-05 17:52:04,647 INFO     [[[0.00000e+00 4.88000e-02 4.60000e+01]
  [0.00000e+00 4.83520e-02 1.79000e+02]
  [0.00000e+00 2.93012e-02 4.74000e+02]
  [0.00000e+00 4.27952e-02 9.90000e+01]
  [0.00000e+00 4.76160e-02 2.78000e+02]
  [0.00000e+00 6.72960e-02 5.50000e+01]
  [0.00000e+00 5.35904e-02 1.42000e+02]
  [0.00000e+00 5.42080e-02 3.58000e+02]
  [2.20000e-09 5.29600e-02 1.37000e+02]
  [0.00000e+00 2.80960e-02 2.47000e+02]]]
2023-04-05 17:52:04,647 INFO     [[[0.00000e+00 4.88000e-02 4.600

1/1 [==============================] - 0s 13ms/step


2023-04-05 17:52:04,687 INFO     Slice 1: Action is 1 Reward is: 0.04730148
2023-04-05 17:52:04,687 INFO     Slice 1: Action is 1 Reward is: 0.04730148
2023-04-05 17:52:04,689 INFO     Testing iteration 2
2023-04-05 17:52:04,689 INFO     Testing iteration 2
2023-04-05 17:52:04,690 INFO     Data received from DU (dl_buffer [bytes], tx_brate downlink [Mbps], ratio_granted_req): 
2023-04-05 17:52:04,690 INFO     Data received from DU (dl_buffer [bytes], tx_brate downlink [Mbps], ratio_granted_req): 
2023-04-05 17:52:04,691 INFO     [[[0.00000e+00 1.59357e-02 9.00000e+00]
  [0.00000e+00 5.31200e-03 4.00000e+00]
  [0.00000e+00 1.32800e-02 1.42000e+02]
  [0.00000e+00 2.75341e-02 1.35000e+02]
  [0.00000e+00 1.89120e-02 1.12000e+02]
  [0.00000e+00 1.06667e-02 1.10000e+01]
  [0.00000e+00 1.52640e-02 2.30000e+01]
  [0.00000e+00 1.06240e-02 6.00000e+00]
  [0.00000e+00 1.59679e-02 8.00000e+00]
  [0.00000e+00 3.21280e-02 9.50000e+01]]]
2023-04-05 17:52:04,691 INFO     [[[0.00000e+00 1.59357e-02 9.0

1/1 [==============================] - 0s 20ms/step


2023-04-05 17:52:04,743 INFO     Slice 2: Action is 2 Reward is: 54.5
2023-04-05 17:52:04,743 INFO     Slice 2: Action is 2 Reward is: 54.5
2023-04-05 17:52:04,744 INFO     Sending this message to the DU: 1,1,2
2023-04-05 17:52:04,744 INFO     Sending this message to the DU: 1,1,2
2023-04-05 17:52:14,749 INFO     Testing iteration 0
2023-04-05 17:52:14,749 INFO     Testing iteration 0
2023-04-05 17:52:14,751 INFO     Data received from DU (dl_buffer [bytes], tx_brate downlink [Mbps], ratio_granted_req): 
2023-04-05 17:52:14,751 INFO     Data received from DU (dl_buffer [bytes], tx_brate downlink [Mbps], ratio_granted_req): 
2023-04-05 17:52:14,752 INFO     [[[0.00000e+00 9.93664e-01 4.10000e+02]
  [9.71400e-07 7.25280e-01 9.00000e+01]
  [2.03000e-07 1.05651e+00 8.00000e+02]
  [8.05400e-07 7.89622e-01 4.65000e+02]
  [1.43300e-07 9.70816e-01 5.00000e+01]
  [0.00000e+00 9.83328e-01 6.04000e+02]
  [0.00000e+00 1.00787e+00 5.14000e+02]
  [1.57800e-06 5.31680e-01 4.20000e+01]
  [0.00000e+00 

1/1 [==============================] - 0s 17ms/step


2023-04-05 17:52:14,794 INFO     Slice 0: Action is 1 Reward is: 0.9022866
2023-04-05 17:52:14,794 INFO     Slice 0: Action is 1 Reward is: 0.9022866
2023-04-05 17:52:14,796 INFO     Testing iteration 1
2023-04-05 17:52:14,796 INFO     Testing iteration 1
2023-04-05 17:52:14,796 INFO     Data received from DU (dl_buffer [bytes], tx_brate downlink [Mbps], ratio_granted_req): 
2023-04-05 17:52:14,796 INFO     Data received from DU (dl_buffer [bytes], tx_brate downlink [Mbps], ratio_granted_req): 
2023-04-05 17:52:14,797 INFO     [[[0.00000e+00 4.76160e-02 7.20000e+01]
  [0.00000e+00 4.94779e-02 1.20000e+02]
  [3.15000e-08 3.19357e-02 5.00000e+00]
  [0.00000e+00 6.27791e-02 5.03000e+02]
  [0.00000e+00 3.45382e-02 7.80000e+01]
  [1.58000e-08 2.66240e-02 6.40000e+01]
  [1.58000e-08 4.35520e-02 5.00000e+00]
  [1.58000e-08 3.21280e-02 5.50000e+01]
  [2.97000e-08 3.21600e-02 2.44000e+02]
  [0.00000e+00 3.30560e-02 3.80000e+01]]]
2023-04-05 17:52:14,797 INFO     [[[0.00000e+00 4.76160e-02 7.200

1/1 [==============================] - 0s 15ms/step


2023-04-05 17:52:14,837 INFO     Slice 1: Action is 1 Reward is: 0.03938669
2023-04-05 17:52:14,837 INFO     Slice 1: Action is 1 Reward is: 0.03938669
2023-04-05 17:52:14,838 INFO     Testing iteration 2
2023-04-05 17:52:14,838 INFO     Testing iteration 2
2023-04-05 17:52:14,839 INFO     Data received from DU (dl_buffer [bytes], tx_brate downlink [Mbps], ratio_granted_req): 
2023-04-05 17:52:14,839 INFO     Data received from DU (dl_buffer [bytes], tx_brate downlink [Mbps], ratio_granted_req): 
2023-04-05 17:52:14,840 INFO     [[[0.00000e+00 5.33333e-03 4.00000e+00]
  [0.00000e+00 1.60643e-02 1.10000e+01]
  [0.00000e+00 1.60640e-02 9.00000e+00]
  [0.00000e+00 1.89237e-02 9.30000e+01]
  [0.00000e+00 1.58720e-02 2.20000e+01]
  [0.00000e+00 1.59360e-02 1.10000e+01]
  [0.00000e+00 1.05920e-02 7.00000e+00]
  [0.00000e+00 1.05600e-02 1.60000e+01]
  [0.00000e+00 1.76640e-02 6.90000e+01]
  [0.00000e+00 1.24800e-02 8.10000e+01]]]
2023-04-05 17:52:14,840 INFO     [[[0.00000e+00 5.33333e-03 4.0

1/1 [==============================] - 0s 14ms/step


2023-04-05 17:52:14,880 INFO     Slice 2: Action is 2 Reward is: 32.3
2023-04-05 17:52:14,880 INFO     Slice 2: Action is 2 Reward is: 32.3
2023-04-05 17:52:14,881 INFO     Sending this message to the DU: 1,1,2
2023-04-05 17:52:14,881 INFO     Sending this message to the DU: 1,1,2
2023-04-05 17:52:24,888 INFO     Testing iteration 0
2023-04-05 17:52:24,888 INFO     Testing iteration 0
2023-04-05 17:52:24,889 INFO     Data received from DU (dl_buffer [bytes], tx_brate downlink [Mbps], ratio_granted_req): 
2023-04-05 17:52:24,889 INFO     Data received from DU (dl_buffer [bytes], tx_brate downlink [Mbps], ratio_granted_req): 
2023-04-05 17:52:24,891 INFO     [[[8.89000e-08 9.77888e-01 5.61000e+02]
  [8.89000e-08 9.77896e-01 5.24000e+02]
  [1.11300e-07 9.67968e-01 7.12000e+02]
  [9.69000e-08 9.76800e-01 1.00000e+03]
  [1.43300e-07 1.13626e+00 6.85000e+02]
  [4.10000e-09 9.82586e-01 3.44000e+02]
  [5.60000e-08 9.82720e-01 4.08000e+02]
  [0.00000e+00 9.66265e-01 6.68000e+02]
  [2.05800e-07 

1/1 [==============================] - 0s 14ms/step


2023-04-05 17:52:24,934 INFO     Slice 0: Action is 1 Reward is: 1.0188566
2023-04-05 17:52:24,934 INFO     Slice 0: Action is 1 Reward is: 1.0188566
2023-04-05 17:52:24,935 INFO     Testing iteration 1
2023-04-05 17:52:24,935 INFO     Testing iteration 1
2023-04-05 17:52:24,936 INFO     Data received from DU (dl_buffer [bytes], tx_brate downlink [Mbps], ratio_granted_req): 
2023-04-05 17:52:24,936 INFO     Data received from DU (dl_buffer [bytes], tx_brate downlink [Mbps], ratio_granted_req): 
2023-04-05 17:52:24,937 INFO     [[[0.0000e+00 3.7440e-02 8.0000e+01]
  [0.0000e+00 4.2816e-02 1.3500e+02]
  [0.0000e+00 6.1952e-02 5.2000e+01]
  [0.0000e+00 3.1648e-02 9.8000e+01]
  [0.0000e+00 2.2656e-02 1.4300e+02]
  [2.7800e-08 5.5104e-02 9.1300e+02]
  [1.5800e-08 3.2512e-02 1.5000e+01]
  [0.0000e+00 4.3552e-02 6.6000e+01]
  [6.5000e-09 3.7504e-02 5.9000e+01]
  [3.1500e-08 2.6752e-02 5.4000e+01]]]
2023-04-05 17:52:24,937 INFO     [[[0.0000e+00 3.7440e-02 8.0000e+01]
  [0.0000e+00 4.2816e-02 

1/1 [==============================] - 0s 14ms/step


2023-04-05 17:52:24,977 INFO     Slice 1: Action is 1 Reward is: 0.0391936
2023-04-05 17:52:24,977 INFO     Slice 1: Action is 1 Reward is: 0.0391936
2023-04-05 17:52:24,978 INFO     Testing iteration 2
2023-04-05 17:52:24,978 INFO     Testing iteration 2
2023-04-05 17:52:24,979 INFO     Data received from DU (dl_buffer [bytes], tx_brate downlink [Mbps], ratio_granted_req): 
2023-04-05 17:52:24,979 INFO     Data received from DU (dl_buffer [bytes], tx_brate downlink [Mbps], ratio_granted_req): 
2023-04-05 17:52:24,980 INFO     [[[0.00000e+00 1.58720e-02 2.50000e+01]
  [0.00000e+00 5.17269e-03 8.00000e+00]
  [0.00000e+00 5.37600e-03 2.00000e+00]
  [0.00000e+00 5.44000e-03 6.00000e+00]
  [0.00000e+00 1.86240e-02 1.04000e+02]
  [0.00000e+00 1.08800e-02 9.00000e+00]
  [0.00000e+00 1.61600e-02 1.40000e+01]
  [0.00000e+00 1.05060e-02 7.00000e+00]
  [0.00000e+00 2.64960e-02 4.60000e+01]
  [0.00000e+00 1.09558e-02 3.40000e+01]]]
2023-04-05 17:52:24,980 INFO     [[[0.00000e+00 1.58720e-02 2.500

1/1 [==============================] - 0s 21ms/step


2023-04-05 17:52:25,041 INFO     Slice 2: Action is 2 Reward is: 25.5
2023-04-05 17:52:25,041 INFO     Slice 2: Action is 2 Reward is: 25.5
2023-04-05 17:52:25,042 INFO     Sending this message to the DU: 1,1,2
2023-04-05 17:52:25,042 INFO     Sending this message to the DU: 1,1,2
2023-04-05 17:52:35,049 INFO     Testing iteration 0
2023-04-05 17:52:35,049 INFO     Testing iteration 0
2023-04-05 17:52:35,050 INFO     Data received from DU (dl_buffer [bytes], tx_brate downlink [Mbps], ratio_granted_req): 
2023-04-05 17:52:35,050 INFO     Data received from DU (dl_buffer [bytes], tx_brate downlink [Mbps], ratio_granted_req): 
2023-04-05 17:52:35,051 INFO     [[[1.43300e-07 1.23946e+00 6.84000e+02]
  [6.89000e-08 9.79072e-01 7.66000e+02]
  [2.72500e-07 9.15008e-01 2.71000e+02]
  [4.25000e-08 1.20899e+00 2.63000e+02]
  [9.09700e-07 8.30361e-01 1.90000e+01]
  [1.17100e-07 9.41472e-01 3.78000e+02]
  [2.76700e-07 9.08562e-01 7.74000e+02]
  [5.97300e-07 7.46924e-01 1.26000e+02]
  [7.89000e-08 

1/1 [==============================] - 0s 14ms/step


2023-04-05 17:52:35,094 INFO     Slice 0: Action is 1 Reward is: 0.9842459
2023-04-05 17:52:35,094 INFO     Slice 0: Action is 1 Reward is: 0.9842459
2023-04-05 17:52:35,095 INFO     Testing iteration 1
2023-04-05 17:52:35,095 INFO     Testing iteration 1
2023-04-05 17:52:35,096 INFO     Data received from DU (dl_buffer [bytes], tx_brate downlink [Mbps], ratio_granted_req): 
2023-04-05 17:52:35,096 INFO     Data received from DU (dl_buffer [bytes], tx_brate downlink [Mbps], ratio_granted_req): 
2023-04-05 17:52:35,097 INFO     [[[0.00000e+00 3.74297e-02 1.13000e+02]
  [0.00000e+00 3.54378e-02 4.00000e+01]
  [0.00000e+00 2.31647e-02 1.86000e+02]
  [1.58000e-08 2.65600e-02 4.20000e+01]
  [0.00000e+00 4.98560e-02 2.91000e+02]
  [0.00000e+00 7.16480e-02 4.49000e+02]
  [0.00000e+00 5.34400e-02 2.29000e+02]
  [0.00000e+00 5.25120e-02 1.90000e+02]
  [3.15000e-08 2.14618e-02 1.50000e+01]
  [0.00000e+00 4.78720e-02 7.10000e+01]]]
2023-04-05 17:52:35,097 INFO     [[[0.00000e+00 3.74297e-02 1.130

1/1 [==============================] - 0s 14ms/step


2023-04-05 17:52:35,137 INFO     Slice 1: Action is 1 Reward is: 0.0419382
2023-04-05 17:52:35,137 INFO     Slice 1: Action is 1 Reward is: 0.0419382
2023-04-05 17:52:35,138 INFO     Testing iteration 2
2023-04-05 17:52:35,138 INFO     Testing iteration 2
2023-04-05 17:52:35,139 INFO     Data received from DU (dl_buffer [bytes], tx_brate downlink [Mbps], ratio_granted_req): 
2023-04-05 17:52:35,139 INFO     Data received from DU (dl_buffer [bytes], tx_brate downlink [Mbps], ratio_granted_req): 
2023-04-05 17:52:35,140 INFO     [[[0.00000e+00 1.60640e-02 2.30000e+01]
  [1.58000e-08 1.06240e-02 2.00000e+01]
  [0.00000e+00 1.19360e-02 8.20000e+01]
  [0.00000e+00 2.18560e-02 2.80000e+01]
  [0.00000e+00 2.67840e-02 2.50000e+01]
  [0.00000e+00 1.59360e-02 1.40000e+01]
  [0.00000e+00 1.05920e-02 1.00000e+01]
  [0.00000e+00 2.16320e-02 1.50000e+01]
  [0.00000e+00 1.07952e-02 1.20000e+01]
  [6.00000e-09 1.67680e-02 5.00000e+01]]]
2023-04-05 17:52:35,140 INFO     [[[0.00000e+00 1.60640e-02 2.300

1/1 [==============================] - 0s 15ms/step


2023-04-05 17:52:35,181 INFO     Slice 2: Action is 2 Reward is: 27.9
2023-04-05 17:52:35,181 INFO     Slice 2: Action is 2 Reward is: 27.9
2023-04-05 17:52:35,182 INFO     Sending this message to the DU: 1,1,2
2023-04-05 17:52:35,182 INFO     Sending this message to the DU: 1,1,2
2023-04-05 17:52:45,189 INFO     Testing iteration 0
2023-04-05 17:52:45,189 INFO     Testing iteration 0
2023-04-05 17:52:45,190 INFO     Data received from DU (dl_buffer [bytes], tx_brate downlink [Mbps], ratio_granted_req): 
2023-04-05 17:52:45,190 INFO     Data received from DU (dl_buffer [bytes], tx_brate downlink [Mbps], ratio_granted_req): 
2023-04-05 17:52:45,191 INFO     [[[9.69000e-08 9.96128e-01 6.98000e+02]
  [4.05600e-07 8.96643e-01 4.34000e+02]
  [1.43300e-07 1.01754e+00 6.75000e+02]
  [2.45000e-08 9.80980e-01 7.26000e+02]
  [2.33000e-08 1.16543e+00 5.29000e+02]
  [4.40000e-07 8.79488e-01 4.07000e+02]
  [0.00000e+00 9.78656e-01 4.73000e+02]
  [1.43300e-07 9.71168e-01 7.56000e+02]
  [1.16900e-07 

1/1 [==============================] - 0s 15ms/step


2023-04-05 17:52:45,231 INFO     Slice 0: Action is 1 Reward is: 0.943739
2023-04-05 17:52:45,231 INFO     Slice 0: Action is 1 Reward is: 0.943739
2023-04-05 17:52:45,232 INFO     Testing iteration 1
2023-04-05 17:52:45,232 INFO     Testing iteration 1
2023-04-05 17:52:45,233 INFO     Data received from DU (dl_buffer [bytes], tx_brate downlink [Mbps], ratio_granted_req): 
2023-04-05 17:52:45,233 INFO     Data received from DU (dl_buffer [bytes], tx_brate downlink [Mbps], ratio_granted_req): 
2023-04-05 17:52:45,234 INFO     [[[0.00000e+00 3.73120e-02 6.70000e+01]
  [3.15000e-08 2.14618e-02 1.10000e+02]
  [0.00000e+00 4.79360e-02 1.37000e+02]
  [0.00000e+00 1.01824e-01 9.70000e+01]
  [0.00000e+00 2.11520e-02 2.80000e+01]
  [9.60000e-09 3.69280e-02 1.07000e+02]
  [0.00000e+00 5.74779e-02 4.70000e+01]
  [0.00000e+00 2.29760e-02 6.00000e+00]
  [0.00000e+00 3.44960e-02 2.61000e+02]
  [1.15000e-08 5.36225e-02 1.17000e+02]]]
2023-04-05 17:52:45,234 INFO     [[[0.00000e+00 3.73120e-02 6.70000

1/1 [==============================] - 0s 14ms/step


2023-04-05 17:52:45,278 INFO     Slice 1: Action is 1 Reward is: 0.04351862
2023-04-05 17:52:45,278 INFO     Slice 1: Action is 1 Reward is: 0.04351862
2023-04-05 17:52:45,279 INFO     Testing iteration 2
2023-04-05 17:52:45,279 INFO     Testing iteration 2
2023-04-05 17:52:45,280 INFO     Data received from DU (dl_buffer [bytes], tx_brate downlink [Mbps], ratio_granted_req): 
2023-04-05 17:52:45,280 INFO     Data received from DU (dl_buffer [bytes], tx_brate downlink [Mbps], ratio_granted_req): 
2023-04-05 17:52:45,281 INFO     [[[0.00000e+00 5.33333e-03 4.00000e+00]
  [0.00000e+00 1.61928e-02 1.20000e+01]
  [0.00000e+00 2.23614e-02 5.70000e+01]
  [0.00000e+00 1.07309e-02 1.10000e+01]
  [0.00000e+00 1.59360e-02 1.20000e+01]
  [0.00000e+00 5.63200e-03 2.30000e+01]
  [0.00000e+00 1.07952e-02 8.00000e+00]
  [0.00000e+00 5.17269e-03 4.00000e+00]
  [0.00000e+00 5.33333e-03 2.00000e+00]
  [0.00000e+00 5.33333e-03 1.20000e+01]]]
2023-04-05 17:52:45,281 INFO     [[[0.00000e+00 5.33333e-03 4.0

1/1 [==============================] - 0s 19ms/step


2023-04-05 17:52:45,336 INFO     Slice 2: Action is 2 Reward is: 14.5
2023-04-05 17:52:45,336 INFO     Slice 2: Action is 2 Reward is: 14.5
2023-04-05 17:52:45,337 INFO     Sending this message to the DU: 1,1,2
2023-04-05 17:52:45,337 INFO     Sending this message to the DU: 1,1,2
2023-04-05 17:52:55,345 INFO     Testing iteration 0
2023-04-05 17:52:55,345 INFO     Testing iteration 0
2023-04-05 17:52:55,347 INFO     Data received from DU (dl_buffer [bytes], tx_brate downlink [Mbps], ratio_granted_req): 
2023-04-05 17:52:55,347 INFO     Data received from DU (dl_buffer [bytes], tx_brate downlink [Mbps], ratio_granted_req): 
2023-04-05 17:52:55,348 INFO     [[[0.00000e+00 9.73536e-01 5.78000e+02]
  [1.10500e-07 9.56992e-01 4.92000e+02]
  [1.10980e-06 6.03552e-01 1.97000e+02]
  [2.70000e-09 1.09677e+00 2.04000e+02]
  [0.00000e+00 9.96800e-01 3.44000e+02]
  [1.17400e-07 9.80128e-01 7.37000e+02]
  [5.70000e-09 9.86217e-01 1.04000e+02]
  [4.73000e-08 1.16405e+00 2.00000e+01]
  [0.00000e+00 

1/1 [==============================] - 0s 15ms/step


2023-04-05 17:52:55,395 INFO     Slice 0: Action is 1 Reward is: 0.9735396
2023-04-05 17:52:55,395 INFO     Slice 0: Action is 1 Reward is: 0.9735396
2023-04-05 17:52:55,396 INFO     Testing iteration 1
2023-04-05 17:52:55,396 INFO     Testing iteration 1
2023-04-05 17:52:55,397 INFO     Data received from DU (dl_buffer [bytes], tx_brate downlink [Mbps], ratio_granted_req): 
2023-04-05 17:52:55,397 INFO     Data received from DU (dl_buffer [bytes], tx_brate downlink [Mbps], ratio_granted_req): 
2023-04-05 17:52:55,398 INFO     [[[0.00000e+00 2.71807e-02 5.60000e+01]
  [0.00000e+00 4.87360e-02 6.10000e+01]
  [0.00000e+00 6.60562e-02 8.32000e+02]
  [0.00000e+00 4.63293e-02 4.20000e+01]
  [5.70000e-09 2.13760e-02 6.40000e+01]
  [0.00000e+00 2.52480e-02 3.70000e+01]
  [1.58000e-08 5.31520e-02 2.02000e+02]
  [0.00000e+00 4.81285e-02 8.90000e+01]
  [0.00000e+00 4.83213e-02 1.45000e+02]
  [0.00000e+00 8.68160e-02 1.17000e+02]]]
2023-04-05 17:52:55,398 INFO     [[[0.00000e+00 2.71807e-02 5.600

1/1 [==============================] - 0s 14ms/step


2023-04-05 17:52:55,439 INFO     Slice 1: Action is 1 Reward is: 0.0471344
2023-04-05 17:52:55,439 INFO     Slice 1: Action is 1 Reward is: 0.0471344
2023-04-05 17:52:55,440 INFO     Testing iteration 2
2023-04-05 17:52:55,440 INFO     Testing iteration 2
2023-04-05 17:52:55,442 INFO     Data received from DU (dl_buffer [bytes], tx_brate downlink [Mbps], ratio_granted_req): 
2023-04-05 17:52:55,442 INFO     Data received from DU (dl_buffer [bytes], tx_brate downlink [Mbps], ratio_granted_req): 
2023-04-05 17:52:55,443 INFO     [[[0.00000e+00 8.09600e-03 9.50000e+01]
  [0.00000e+00 2.10560e-02 2.62000e+02]
  [0.00000e+00 1.09440e-02 9.00000e+00]
  [0.00000e+00 2.64960e-02 3.20000e+01]
  [0.00000e+00 1.06240e-02 8.00000e+00]
  [0.00000e+00 1.06024e-02 8.00000e+00]
  [0.00000e+00 6.11200e-03 2.90000e+01]
  [0.00000e+00 1.66104e-02 1.00000e+01]
  [0.00000e+00 1.72480e-02 7.90000e+01]
  [0.00000e+00 1.05600e-02 1.40000e+01]]]
2023-04-05 17:52:55,443 INFO     [[[0.00000e+00 8.09600e-03 9.500

1/1 [==============================] - 0s 16ms/step


2023-04-05 17:52:55,488 INFO     Slice 2: Action is 1 Reward is: 54.6
2023-04-05 17:52:55,488 INFO     Slice 2: Action is 1 Reward is: 54.6
2023-04-05 17:52:55,489 INFO     Sending this message to the DU: 1,1,1
2023-04-05 17:52:55,489 INFO     Sending this message to the DU: 1,1,1


KeyboardInterrupt: 